config/routes.rb
Starter::Application.routes.draw do
  match "sign_out" => "sessions#destroy", :via => [:get, :delete, :post]
  get "sign_in" => "sessions#new"
  post "sign_in" => "sessions#create"
  
  root :to => "home#index", :as => :home
  
  get "contact" => "home#contact"
  get "about" => "home#about"
  get "denied" => "home#denied"
  
  get "dashboard" => "user#dashboard"
  get "profile" => "user#profile"
  put "profile" => "user#save"
  get "settings" => "user#settings"
  post "settings" => "user#save_settings"
  get "password" => "user#password"
  post "password" => "user#change_password"
  
  match "search" => "search#index", :via => [:get, :post]
  
  resources :sessions
  
  resources :staff do
    resources :roles
    
    resources :photos do 
      member do
        get "download"
        put "default"
      end
    end
    
    member do
      get "password"
      put "password" => "staff#reset_password"
      get "terminate"
      put "terminate" => "staff#save_terminate"
      get "nok"
      put "nok" => "staff#save_nok"
      post "nok" => "staff#save_nok"
      get "employment"
      put "employment" => "staff#update_employment"
      put "unlock"
      put "lock" 
    end
    
    collection do
      get "search"
      get "search/active" => "staff#search_active"
      get "terminated" => "staff#inactive"
      get "recent"
    end
  end
  
  namespace :admin do
    resources :organisations do
      resources :roles, :controller => "permissions"
      resources :locations
    end
  end
       
  match "*path" => "application#render_not_found"
end

app/controllers/admin/locations_controller.rb
class Admin::LocationsController < Admin::GroupController
  respond_to :html, :json
  
  expose(:group) { Group.find params[:organisation_id] }
  expose(:area) { "organisations" }

  expose(:locations) { Group.find_all_by_code_and_is_primary group.code, false }
  expose(:location) do
    if params[:id]
      Group.find(params[:id]) 
    else
      Group.new
    end
  end
  
  def show
    render "index"
  end
  
  def index
    flash.now[:warning] = t :error if locations.empty?
    
    respond_with locations
  end
  
  def new
  end
  
  def create
    location = group.children.build(params[:group])
    location.setup_as_location
    
    if location.save
      flash.now.notice = t :success
      render "index"
    else
      flash.now.alert = t :error
      render "new"
    end  
  end
  
  def update
    if location.update_attributes(params[:group])
      flash.now.notice = t :success
    else
      flash.now.alert = t :error
    end
    render "index"
  end
end

app/views/admin/locations/_form.html.slim
= f.inputs do
	= f.input :name
	== render :partial => "form/address", :locals => { :f => f }
	fieldset
		= label_tag :organisation do	
			= check_box_tag :organisation 
			span Use Organisation Address?
	= submit f, :save, group, :update
	= f.fields_for group do |g|
		= g.input :address_line_1, :as => :hidden
		= g.input :address_locality, :as => :hidden
		= g.input :address_area, :as => :hidden
		= g.input :address_country, :as => :hidden
		= g.input :address_postcode, :as => :hidden

app/views/admin/locations/_location.html.slim
article.item
	.heading
		span= location.name
		ul.links data-area="organisations"
			=menu :edit, edit_admin_organisation_location_path(group, location), group, :update, 'locations', 'edit'
		a.show href="." =raw("show&rarr;")
		a.hide href="." =raw("hide&uarr;")

	.detail.no-bottom
		.row.half-bottom
			.three.columns= "Address"
			.six.columns
				strong= location.address

app/views/admin/locations/edit.html.slim
= content_for :sidebar do
	== render :partial => "sidebar/organisation", :locals => { :organisation => group }
	
== render :partial => "admin/organisations/menu"
	
= semantic_form_for location, :url => admin_organisation_location_path(group, location), :validate => true do |f|
	== render :partial => "form", :locals => { :f => f }

app/views/admin/locations/index.html.slim
= content_for :sidebar do
	== render :partial => "sidebar/organisation", :locals => { :organisation => group }
	
== render :partial => "admin/organisations/menu"

== render :partial => "location", :collection => locations

app/views/admin/locations/new.html.slim
= content_for :sidebar do
	== render :partial => "sidebar/organisation", :locals => { :organisation => group }
	
== render :partial => "admin/organisations/menu"
	
= semantic_form_for location, :url => admin_organisation_locations_path(group), :validate => true do |f|
	== render :partial => "form", :locals => { :f => f }