config/routes.rb
Starter::Application.routes.draw do
  match "sign_out" => "sessions#destroy", :via => [:get, :delete, :post]
  get "sign_in" => "sessions#new"
  post "sign_in" => "sessions#create"
  
  root :to => "home#index", :as => :home
  
  get "contact" => "home#contact"
  get "about" => "home#about"
  get "denied" => "home#denied"
  
  get "dashboard" => "user#dashboard"
  get "profile" => "user#profile"
  put "profile" => "user#save"
  get "settings" => "user#settings"
  post "settings" => "user#save_settings"
  get "password" => "user#password"
  post "password" => "user#change_password"
  
  match "search" => "search#index", :via => [:get, :post]
  
  resources :sessions
  
  resources :staff do
    resources :roles
    
    resources :photos do 
      member do
        get "download"
        put "default"
      end
    end
    
    member do
      get "password"
      put "password" => "staff#reset_password"
      get "terminate"
      put "terminate" => "staff#save_terminate"
      get "nok"
      put "nok" => "staff#save_nok"
      post "nok" => "staff#save_nok"
      get "employment"
      put "employment" => "staff#update_employment"
      put "unlock"
      put "lock" 
    end
    
    collection do
      get "search"
      get "search/active" => "staff#search_active"
      get "terminated" => "staff#inactive"
      get "recent"
    end
  end
  
  namespace :admin do
    resources :organisations do
      resources :roles, :controller => "permissions"
      resources :locations
    end
  end
       
  match "*path" => "application#render_not_found"
end

app/models/permission.rb
class Permission < ActiveRecord::Base
  scope :by_resource, lambda { |r| where(:resource => r) }

  belongs_to :role

  attr_accessible :action, :resource, :resource_id

  def self.resources
    %w[Staff Patient Group User]
  end
  
  def self.permissions
    [["No Access", :no_access], ["Read Only", :read_only], ["Editor", :editor], ["Full Control", :full_control]]
  end  
end
# == Schema Information
#
# Table name: permissions
#
#  id          :integer         not null, primary key
#  action      :string(255)
#  resource    :string(255)
#  resource_id :integer
#  role_id     :integer         not null
#  created_at  :datetime
#  updated_at  :datetime
#

app/controllers/admin/permissions_controller.rb
class Admin::PermissionsController < Admin::GroupController
  respond_to :html, :json

  expose(:group) { Group.find params[:organisation_id] }
  expose(:area) { "organisations" }

  expose(:roles) { group.roles }
  expose(:role)
  
  def show
    render "index"
  end
  
  def index
    flash.now[:warning] = t :error if roles.empty?

    respond_with roles
  end

  def new
  end

  def create
    role = group.roles.build(params[:role])
    
    if group.save
      flash.now.notice = t :success
      render "index"
    else
      flash.now.alert = t :error
      render "new"
    end  
  end
  
  def update    
    if role.update_attributes(params[:role])
      role.update_permissions(params[:permissions])
      
      flash.now.notice = t :success
    else
      flash.now.alert = t :error
    end
    render "index"
  end
end

app/helpers/permissions_helper.rb
module PermissionsHelper
  def permission_for_display(role, resource)
    permission(role, resource)[0]
  end  
  
  def permission_for(role, resource)
    permission(role, resource)[1]
  end

  private
  
  def permission(role, resource)
    all = Permission.permissions    
    permission = role.permissions.by_resource(resource.downcase).first

    if !permission.nil?
      all.detect { |a| a.include?(permission.action.to_sym) }
    else
      all.detect { |a| a.include?(:no_access) }
    end
  end
end

app/views/admin/permissions/_role.html.slim
article.list data-index=role_counter
	.view.row.remove-bottom
		.five.columns
			strong=role.name
		.five.columns
			- Permission.resources.each do |resource|
				div
					.two.columns=resource
					.three.columns
						span.small
							= permission_for_display(role, resource)
		
	- if can? :update, group
		.edit.row.remove-bottom
			= semantic_form_for role, :url => admin_organisation_role_path(group, role), :validate => true, :namespace => "permissions_#{role_counter}" do |f|
				.five.columns
					= f.inputs do
						= f.input :name, :label => false
						= submit f, "Save", group, :update
				.five.columns.pad
					- Permission.resources.each do |resource|
						div
							.two.columns=resource
							.three.columns
								fieldset
									= select("permissions", resource.downcase, Permission.permissions, { :selected => permission_for(role, resource) }, :class => "inline")
	

app/views/admin/permissions/index.html.slim
= content_for :sidebar do
	== render :partial => "sidebar/organisation", :locals => { :organisation => group }
	
== render :partial => "admin/organisations/menu"

== render :partial => "role", :collection => roles

app/views/admin/permissions/new.html.slim
= content_for :sidebar do
	== render :partial => "sidebar/organisation", :locals => { :organisation => group }
	
== render :partial => "admin/organisations/menu"
	
= semantic_form_for role, :url => admin_organisation_roles_path(group), :validate => true do |f|
	= f.inputs :name
	= submit f, "Save", group, :update