config/routes.rb
Starter::Application.routes.draw do
  match "sign_out" => "sessions#destroy", :via => [:get, :delete, :post]
  get "sign_in" => "sessions#new"
  post "sign_in" => "sessions#create"
  
  root :to => "home#index", :as => :home
  
  get "contact" => "home#contact"
  get "about" => "home#about"
  get "denied" => "home#denied"
  
  get "dashboard" => "user#dashboard"
  get "profile" => "user#profile"
  put "profile" => "user#save"
  get "settings" => "user#settings"
  post "settings" => "user#save_settings"
  get "password" => "user#password"
  post "password" => "user#change_password"
  
  match "search" => "search#index", :via => [:get, :post]
  
  resources :sessions
  
  resources :staff do
    resources :roles
    
    resources :photos do 
      member do
        get "download"
        put "default"
      end
    end
    
    member do
      get "password"
      put "password" => "staff#reset_password"
      get "terminate"
      put "terminate" => "staff#save_terminate"
      get "nok"
      put "nok" => "staff#save_nok"
      post "nok" => "staff#save_nok"
      get "employment"
      put "employment" => "staff#update_employment"
      put "unlock"
      put "lock" 
    end
    
    collection do
      get "search"
      get "search/active" => "staff#search_active"
      get "terminated" => "staff#inactive"
      get "recent"
    end
  end
  
  namespace :admin do
    resources :organisations do
      resources :roles, :controller => "permissions"
      resources :locations
    end
  end
       
  match "*path" => "application#render_not_found"
end

app/controllers/search_controller.rb
class SearchController < AuthenticatedController
  respond_to :html, :json
    
  skip_before_filter :authenticate!, :only => :index
    
  expose(:query) { params[:q] || "" }
  expose(:search) { params[:s] || "" }
  expose(:type) { (params[:t] || "").singularize.titleize }
  expose(:people) { Searcher.search(query, type, skip, PAGE_SIZE, security_key) } 
  expose(:total) { Searcher.count(query, type, security_key) } 
  
  def index  
    if total == 1 && request.format == :html
      redirect_to people.first.uri
    else
      build_message query, people.count, total
      
      respond_to do|format|
        format.html
        format.json do
          render :json => 
            { :page => page, :skip => skip, :limit => PAGE_SIZE, :total => total, :query => query, :results => people }
        end
      end
    end
  end
  
  private 
  
  def build_message(query, paged, total)
    if query.empty?
      flash.now.alert = t(:error)
      return
    end
    
    result = t(:results)
    count = total

    result = result.singularize if count == 1
    count = t(:no) if count == 0
    
    message = "#{count} #{result} #{t(:found)}"
    
    flash.now.notice = message if paged > 0
    flash.now[:warning] = message if paged == 0    
  end
end

app/helpers/search_helper.rb
module SearchHelper
  def for_query(query)
    raw "for &quot;#{content_tag :strong, query}&quot;"
  end
end

app/views/search/_group.html.slim
article.search
	= image_tag "group.png"
	.info
		span.resource data-resource="organisations"
			strong= group.name
		.content
			= group.code
	.open
		= link_to raw(t(:open) + "&rarr;"), admin_organisation_path(group)

app/views/search/_paging.html.slim
- if total > limit
	.paging
		div.search
			= t(:showing) + " #{skip + 1} " + t(:to) + " "
			- if skip + limit > total
				= total
			- else
				= skip + limit
			= " " + t(:of) + " #{total}"
			= link_to_if page > 1, raw(" &larr;" + t(:previous)), :controller => "search", :q => query, :p => page-1
			| &nbsp;|&nbsp;
			= link_to_if skip+limit < total, raw(t(:next) + "&rarr;"), :controller => "search", :q => query, :p => page+1

app/views/search/_person.html.slim
article.search
	== render :partial => "search/photo", :locals => { :person => person }
	.info
		span.resource data-resource=person.resource data-area=person.area
			strong= person.full_name
			span
				- if person.type == "Staff"
					span.info= person.job_title
				- if person.type == "Staff" && !person.left_on.nil?
					span.info= t(:terminated)
		.content
			- if !person.phone.nil? && !person.phone.empty?
				span.info= person.phone
			- if person.user
				a href=mailto(person.user.email)
					= person.user.email
	.open
		a href=person.uri
			= raw(t(:open) + "&rarr;");

app/views/search/_photo.html.slim
- if person.photos.is_default.empty?
	= image_tag "noprofile.png"
- else
	= image_tag person.profile_photo.image.url(:thumbnail)

app/views/search/_search.html.slim
=form_tag search_path, :id => "search_form", :class => "eleven columns remove-bottom shift-left" do
	=text_field_tag :search, params[:q], :class => "eleven columns remove-bottom", :name => "q", :placeholder => raw("search &rarr;")

app/views/search/index.html.slim
= content_for :sidebar do
	=title :title
	=for_query query

== render :partial => "paging"
== render :partial => "person", :collection => people	
== render :partial => "paging"