config/routes.rb
Starter::Application.routes.draw do
  match "sign_out" => "sessions#destroy", :via => [:get, :delete, :post]
  get "sign_in" => "sessions#new"
  post "sign_in" => "sessions#create"
  
  root :to => "home#index", :as => :home
  
  get "contact" => "home#contact"
  get "about" => "home#about"
  get "denied" => "home#denied"
  
  get "dashboard" => "user#dashboard"
  get "profile" => "user#profile"
  put "profile" => "user#save"
  get "settings" => "user#settings"
  post "settings" => "user#save_settings"
  get "password" => "user#password"
  post "password" => "user#change_password"
  
  match "search" => "search#index", :via => [:get, :post]
  
  resources :sessions
  
  resources :staff do
    resources :roles
    
    resources :photos do 
      member do
        get "download"
        put "default"
      end
    end
    
    member do
      get "password"
      put "password" => "staff#reset_password"
      get "terminate"
      put "terminate" => "staff#save_terminate"
      get "nok"
      put "nok" => "staff#save_nok"
      post "nok" => "staff#save_nok"
      get "employment"
      put "employment" => "staff#update_employment"
      put "unlock"
      put "lock" 
    end
    
    collection do
      get "search"
      get "search/active" => "staff#search_active"
      get "terminated" => "staff#inactive"
      get "recent"
    end
  end
  
  namespace :admin do
    resources :organisations do
      resources :roles, :controller => "permissions"
      resources :locations
    end
  end
       
  match "*path" => "application#render_not_found"
end

app/views/shared/_confirm.html.slim
#confirm
	.message.question= t(:confirm)
	.questions
		a.yes= t(:yes)
		a.no= t(:no)

app/views/shared/_empty.html.slim
- if count == 0
	article.row.remove-bottom
		.message.warning= (message ||= t(:no_data))

app/views/shared/_footer.html.slim
footer.eleven.columns.offset-by-three.shift-left
	span#colophon
		| Engineered by 
		a href="http://perceptal.co.uk"
			| Perceptal Web Labs 
		| 2011
	span#response
		= response_time 

app/views/shared/_header.html.slim
header.row.half-bottom
	h2#home.three.columns.alpha.remove-bottom.shift-right
		= link_to t(:name), home_url
		
	= render :partial => "search/search"
	= render :partial => "sessions/links"

app/views/shared/_menu.html.slim
nav#menu.two.columns.omega  
	ul class=area_name
		li.user data-area='user'
			=link :dashboard, dashboard_path, User

		li.staff data-area='staff'
			=link :staff, staff_index_path, Staff

		li.organisations data-area='organisations'
			=link :administration, admin_organisations_path, Group

		li.loading Loading...

app/views/shared/_message.html.slim
#dialog
	span.message.info= raw flash.notice
	span.message.warning= raw flash[:warning]
	span.message.error= raw flash.alert
	span.message.loading
	a.close= t(:close)

app/views/shared/_paging.html.slim
- if total > limit
	.paging	
		div class=controller_name
			= t(:showing) + " #{skip + 1} " + t(:to) + " "
			- if skip + limit > total
				= total
			- else
				= skip + limit
			= " " + t(:of) + " #{total}"
			= link_to_if page > 1, raw(" &larr;" + t(:previous)), :controller => controller_name, :action => action_name, :p => page-1
			| &nbsp;|&nbsp;
			= link_to_if skip+limit < total, raw(t(:next) + "&rarr;"), :controller => controller_name, :action => action_name, :p => page+1

app/views/shared/_response.html.slim
.response
	= response_time